StudentsCourse/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('student.urls')),
]

student/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from student.views import index, add_student, delete_student, edit_student, eletive, search, login, register, logout, \
    edit_admin

urlpatterns = [
    path('', index),
    path('login/', login),
    re_path('edit_admin_user/(\d+)', edit_admin),
    path('logout/', logout),
    path('register/', register),
    path('index/', index),
    path('add/', add_student),
    re_path('delete/(\d+)', delete_student),
    re_path('edit/(\d+)', edit_student),
    # 选课
    re_path('eletive/', eletive),
    # 搜索
    re_path('search/', search),
]

student/models.py
from django.db import models


# Create your models here.

class Student(models.Model):
    sex_choice = (
        (0, '女'),
        (1, '男'),
        (2, '保密'),
    )
    name = models.CharField(max_length=32, null=False, verbose_name='姓名')
    age = models.SmallIntegerField(default=18, verbose_name='年龄')
    sex = models.SmallIntegerField(choices=sex_choice, verbose_name='性别')
    birthday = models.DateField(verbose_name='生日')
    tel = models.CharField(max_length=11, null=True, verbose_name='电话号码')
    addr = models.CharField(max_length=64, null=True, verbose_name='家庭住址')

    # 建立一对多关系：数据库关联字段 clas_id
    clas = models.ForeignKey(to='Clas', on_delete=models.CASCADE, related_name='student_list')

    # 建立多对多关系：创建第三张关系表
    course = models.ManyToManyField('Course', db_table='db_student2course', related_name='students')

    # 一对一的关系：建立关联字段
    # stu_detail = models.OneToOneField('StudentDetail', on_delete=models.CASCADE, related_name='stu')

    class Meta:
        db_table = 'db_student'


class Clas(models.Model):
    name = models.CharField(max_length=32, null=False, verbose_name='班级名称')

    class Meta:
        db_table = "db_class"


class Course(models.Model):
    title = models.CharField(max_length=48, null=False, verbose_name='课程名称')
    credit = models.IntegerField(verbose_name='学分', default=3)
    teacher = models.CharField(max_length=32, verbose_name='教师', null=True)
    classTime = models.CharField(max_length=32, verbose_name='上课时间', null=True)
    classAddr = models.CharField(max_length=32, verbose_name='上课地点', null=True)

    class Meta:
        db_table = "db_course"


class StudentDetail(models.Model):
    tel = models.CharField(max_length=11, verbose_name='电话号码')
    addr = models.CharField(max_length=64, verbose_name='地址')

    class Meta:
        db_table = 'db_stu_detail'


from django.contrib.auth.models import AbstractUser


class AdminUser(AbstractUser):
    pass

    class Meta:
        db_table = 'db_admin_user'

student/views.py
from django.shortcuts import render, HttpResponse, redirect
from .models import Student, Clas, Course, StudentDetail, AdminUser
from django.contrib import auth


# Create your views here.


def index(request):
    if request.user.username:
        # 获取所有学生数据
        student_list = Student.objects.all()

        return render(request, 'student/index.html', {'student_list': student_list})
    else:
        return redirect('/login')


def add_student(request):
    if request.method == 'GET':
        class_list = Clas.objects.all()
        course_list = Course.objects.all()

        return render(request, 'student/add_stu.html', {'class_list': class_list, 'course_list': course_list})
    else:
        # 获取客户端数据
        # name = request.POST.get('name')
        # age = request.POST.get('age')
        # sex = request.POST.get('sex')
        # birthday = request.POST.get('birthday')
        # clas_id = request.POST.get('clas_id')
        # tel = request.POST.get('tel')
        # addr = request.POST.get('addr')

        stu = Student.objects.create(**request.POST.dict())

        # <QueryDict: {'name': ['小明'], 'age': ['23'], 'sex': ['1'], 'birthday': ['2022-10-11'], 'tel': ['1212'], 'addr': ['河北'], 'clas_id': ['1']}>
        # 添加到数据库
        return redirect('/index')


def delete_student(request, del_id):
    student = Student.objects.get(id=del_id)

    if request.method == "GET":
        return render(request, 'student/delete_stu.html', {'student': student})
    else:

        Student.objects.get(id=del_id).delete()

        return redirect('/index')


def edit_student(request, edit_id):
    edit_stu = Student.objects.get(id=edit_id)
    if request.method == 'GET':

        class_list = Clas.objects.all()
        course_list = Course.objects.all()

        return render(request, "student/edit_stu.html",
                      {'edit_stu': edit_stu, 'course_list': course_list, 'class_list': class_list})
    else:
        data = request.POST.dict()

        Student.objects.filter(id=edit_id).update(**data)

        return redirect('/index')


def eletive(request):
    if request.method == 'GET':
        course_list = Course.objects.all()
        return render(request, 'student/course.html', {'course_list': course_list})
    else:

        course_id_list = request.POST.getlist('course_id_list')
        stu_id = 9
        stu = Student.objects.get(id=stu_id)
        stu.course.set(course_id_list)
        # print(course_id_list)

        return redirect('/student/index')


def search(request):
    student_list = []
    keyword = request.GET.get('keyword')
    cate = request.GET.get("cate")

    if cate == 'name':
        student_list = Student.objects.filter(name__contains=keyword)
    elif cate == 'class':
        student_list = Student.objects.filter(clas__name=keyword)

    return render(request, "student/search.html", {'student_list': student_list, 'keyword': keyword, "cate": cate})


def login(request):
    erro_msg = ''
    if request.method == 'GET':
        return render(request, 'student/login.html', {'erro_msg': erro_msg})

    else:
        username = request.POST.get('loginUsername')
        password = request.POST.get('loginPassword')
        user = auth.authenticate(username=username, password=password)
        if user:

            auth.login(request, user)
            return redirect('/index')
        else:
            erro_msg = '用户名或密码错误'
            return render(request, 'student/login.html', {'erro_msg': erro_msg})


def register(request):
    if request.method == 'GET':
        return render(request, 'student/register.html')
    else:
        username = request.POST.get('registerUsername')
        password = request.POST.get('registerPassword')
        email = request.POST.get('registerEmail')
        AdminUser.objects.create_user(username=username, password=password, email=email)
        return redirect('/login')


def logout(request):
    auth.logout(request)

    return redirect('/login')


def edit_admin(request, admin_id):
    user = AdminUser.objects.get(id=admin_id)
    if request.method == 'GET':

        return render(request, 'student/edit_admin.html', {'username': user})
    else:
        user = request.user
        new_password = request.POST.get('newPassword')
        user.set_password(new_password)
        user.save()

        return redirect('/index')

templates/student/add_stu.html
{% extends "student/base.html" %}

{% block content %}
    <section class="forms">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header d-flex align-items-center">
                    <h4>添加学生</h4>
                </div>
                <div class="card-body">
                    <p>Lorem ipsum dolor sit amet consectetur.</p>
                    <form action="/add/" method="post">
                        <div class="form-group">
                            <label>姓名</label>
                            <input type="text" placeholder="Name" class="form-control" name="name">
                        </div>
                        <div class="form-group">
                            <label>年龄</label>
                            <input type="text" placeholder="Age" class="form-control" name="age">
                        </div>
                        <div class="form-group">
                            <label>性别</label>
                            <select name="sex" id="" class="form-control">
                                <option value="1">男</option>
                                <option value="0">女</option>
                                <option value="2">保密</option>
                            </select>
                        </div>

                        <div class="form-group">
                            <label>生日</label>
                            <input name="birthday" type="date" placeholder="Birthday" class="form-control">
                        </div>
                        <div class="form-group">
                            <label>电话</label>
                            <input name='tel' type="text" placeholder="Telephone Number" class="form-control">
                        </div>
                        <div class="form-group">
                            <label>家庭住址</label>
                            <input type="text" placeholder="Address" class="form-control" name="addr">
                        </div>

                        <div class="form-group">
                            <label>班级</label>
                            <select name="clas_id" id="" class="form-control">
                                {% for class in class_list %}
                                    <option value="{{ class.id }}">{{ class.name }}</option>
                                {% endfor %}
                            </select>
                        </div>

                        <div class="form-group">
                            <input type="submit" value="添加学生" class="btn btn-primary">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/student/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>学生信息管理系统</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="https://www.jq22.com/jquery/bootstrap-4.2.1.css">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="https://www.jq22.com/jquery/font-awesome.4.7.0.css">
    <!-- Fontastic Custom icon font-->
    <link rel="stylesheet" href="../../static/css/fontastic.css">
    <!-- Google fonts - Roboto -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700">
    <!-- jQuery Circle-->
    <link rel="stylesheet" href="../../static/css/grasp_mobile_progress_circle-1.0.0.min.css">
    <!-- Custom Scrollbar-->
    <link rel="stylesheet" href="../../static/vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.css">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="../../static/css/style.default.css" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="../../static/css/custom.css">
    <!-- Favicon-->
    <link rel="shortcut icon" href="../../static/img/favicon.ico">
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>
<body>
<!-- Side Navbar -->
<nav class="side-navbar">
    <div class="side-navbar-wrapper">
        <!-- Sidebar Header    -->
        <div class="sidenav-header d-flex align-items-center justify-content-center">
            <!-- User Info-->
            <div class="sidenav-header-inner text-center"><a href="/index"><img
                    src="../../static/img/avatar-7.jpg" alt="person" class="img-fluid rounded-circle"></a>
                <h2 class="h5">Nathan Andrews</h2><span>Web Developer</span>
            </div>
            <!-- Small Brand information, appears on minimized sidebar-->
            <div class="sidenav-header-logo"><a href="index.html" class="brand-small text-center">
                <strong>B</strong><strong class="text-primary">D</strong></a></div>
        </div>
        <!-- Sidebar Navigation Menus-->
        <div class="main-menu">
            <h5 class="sidenav-heading">Main</h5>
            <ul id="side-main-menu" class="side-menu list-unstyled">
                <li><a href="/index"> <i class="icon-home"></i>首页 </a></li>
                <li><a href="#"> <i class="icon-form"></i>功能待完善.. </a></li>
                {#                <li><a href="/eletive"> <i class="icon-form"></i>功能待完善.. </a></li>#}
            </ul>
        </div>

    </div>
</nav>
<div class="page">
    <!-- navbar-->
    <header class="header">
        <nav class="navbar">
            <div class="container-fluid">
                <div class="navbar-holder d-flex align-items-center justify-content-between">
                    <div class="navbar-header"><a id="toggle-btn" href="#" class="menu-btn"><i
                            class="icon-bars"> </i></a><a href="index.html" class="navbar-brand">
                        <div class="brand-text d-none d-md-inline-block"><strong
                                class="text-primary">学生信息管理系统</strong></div>
                    </a></div>
                    <ul class="nav-menu list-unstyled d-flex flex-md-row align-items-md-center">
                        <li class="nav-item dropdown">
                            <a id="languages" rel="nofollow" data-target="#" href="#" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false"
                               class="nav-link language dropdown-toggle"><span
                                    class="d-none d-sm-inline-block">{{ request.user.username }}</span></a>
                            <ul aria-labelledby="languages" class="dropdown-menu">
                                <li><a rel="nofollow" href="#" class="dropdown-item"> <span>个人中心</span></a></li>
                                <li><a rel="nofollow" href="/edit_admin_user/{{ request.user.id }}"
                                       class="dropdown-item"> <span>修改密码</span></a></li>
                            </ul>
                            <!-- Log out-->
                        <li class="nav-item"><a href="/logout/" class="nav-link logout"> <span
                                class="d-none d-sm-inline-block">Logout</span><i class="fa fa-sign-out"></i></a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    {% block content %}

    {% endblock content %}

    <footer class="main-footer">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-6">
                    <p>Copyright &copy; 2022.by SongYanpeng.</p>
                </div>
                <div class="col-sm-6 text-right">


                </div>
            </div>
        </div>
    </footer>
</div>
<!-- JavaScript files-->
<script src="https://www.jq22.com/jquery/jquery-1.10.2.js"></script>
<script src="../../static/vendor/popper.js/umd/popper.min.js"></script>
<script src="https://www.jq22.com/jquery/bootstrap-4.2.1.js"></script>
<script src="../../static/js/grasp_mobile_progress_circle-1.0.0.min.js"></script>
<script src="../../static/vendor/jquery.cookie/jquery.cookie.js"></script>
<script src="../../static/vendor/chart.js/Chart.min.js"></script>
<script src="../../static/vendor/jquery-validation/jquery.validate.min.js"></script>
<script src="../../static/vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js"></script>
<script src="../../static/js/charts-home.js"></script>
<!-- Main File-->
<script src="../../static/js/front.js"></script>
</body>
</html>

templates/student/course.html
{% extends "student/base.html" %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h4>选修课程</h4>
                </div>
                <div class="card-body">
                    {#                    <p><a href="/student/add" class="btn btn-info">添加学生</a></p>#}
                    <div class="table-responsive">
                        <form action="" method="post">
                            <table class="table table-striped table-hover">
                                <thead>
                                <tr>
                                    <th>选择</th>
                                    <th>序号</th>
                                    <th>课程名称</th>
                                    <th>讲师</th>
                                    <th>学分</th>
                                    <th>上课时间</th>
                                    <th>上课教室</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for course in course_list %}
                                    <tr>
                                    <td><input type="checkbox" value="{{ course.id }}" name="course_id_list" id=""></td>
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ course.title }}</td>
                                        <td>{{ course.teacher }}</td>
                                        <td>{{ course.credit }}</td>
                                        <td>{{ course.classTime }}</td>
                                        <td>{{ course.classAddr }}</td>
                                    </tr>
                                {% endfor %}


                                </tbody>
                            </table>
                            <input type="submit" class="btn btn-success pull-right">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/student/delete_stu.html
{% extends "student/base.html" %}

{% block content %}
    <div class="col-md-10">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>学生信息</h4>
            </div>
            <div class="card-body">
                <p>
                <table class="table table-striped table-hover">
                    <tbody>

                    <tr>
                        <td>{{ student.name }}</td>
                        <td>{{ student.age }}</td>
                        <td>{{ student.get_sex_display }}</td>
                        <td>{{ student.birthday|date:'Y-m-d' }}</td>
                        <td>{{ student.clas.name }}</td>
                    </tr>


                    </tbody>
                </table>
                </p>
                <form class="form-horizontal" method="post">
                    <div class="col-sm-10 offset-sm-2">
                        <input type="submit" value="确认删除" class="btn btn-danger pull-right">
                    </div>
            </div>
            </form>
        </div>
    </div>
    </div>
{% endblock content %}

templates/student/edit_admin.html
{% extends "student/base.html" %}

{% block content %}
    <section class="forms">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header d-flex align-items-center">
                    <h4>修改密码</h4>
                </div>
                <div class="card-body">
                    <form action="" method="post">
                        <div class="form-group">
                            <label>用户名</label>
                            <input type="text" value="{{ username }}" placeholder="Name" class="form-control"
                                   name="name">
                        </div>
                        <div class="form-group">
                            <label>新密码</label>
                            <input type="password"  placeholder="请输入新密码" class="form-control"
                                   name="newPassword">
                        </div>

                        <div class="form-group">
                            <input type="submit" value="修改" class="btn btn-primary">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

templates/student/edit_stu.html
{% extends "student/base.html" %}

{% block content %}
    <section class="forms">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header d-flex align-items-center">
                    <h4>编辑学生信息</h4>
                </div>
                <div class="card-body">
                    <form action="" method="post">
                        <div class="form-group">
                            <label>姓名</label>
                            <input type="text" value="{{ edit_stu.name }}" placeholder="Name" class="form-control"
                                   name="name">
                        </div>
                        <div class="form-group">
                            <label>年龄</label>
                            <input type="text" value="{{ edit_stu.age }}" placeholder="Age" class="form-control"
                                   name="age">
                        </div>
                        <div class="form-group">
                            <label>性别</label>
                            <select name="sex" id="" class="form-control">
                                {% if edit_stu.sex == 1 %}
                                    <option value="1" selected>男</option>
                                    <option value="0">女</option>
                                    <option value="2">保密</option>
                                {% elif edit_stu.sex == 0 %}
                                    <option value="1">男</option>
                                    <option value="0" selected>女</option>
                                    <option value="2">保密</option>
                                {% else %}
                                    <option value="1">男</option>
                                    <option value="0">女</option>
                                    <option value="2" selected>保密</option>
                                {% endif %}
                            </select>
                        </div>

                        <div class="form-group">
                            <label>生日</label>
                            <input name="birthday" value="{{ edit_stu.birthday|date:'Y-m-d' }}" type="date"
                                   placeholder="Birthday" class="form-control">
                        </div>
                        <div class="form-group">
                            <label>电话</label>
                            <input name='tel' value="{{ edit_stu.tel }}" type="text" placeholder="Telephone Number"
                                   class="form-control">
                        </div>
                        <div class="form-group">
                            <label>家庭住址</label>
                            <input type="text" value="{{ edit_stu.addr }}" placeholder="Address" class="form-control"
                                   name="addr">
                        </div>

                        <div class="form-group">
                            <label>班级</label>
                            <select name="clas_id" id="" class="form-control">
                                {% for class in class_list %}
                                    {% if class == edit_stu.clas %}
                                        <option selected value="{{ class.id }}">{{ class.name }}</option>
                                    {% else %}
                                        <option value="{{ class.id }}">{{ class.name }}</option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                        </div>


                        <div class="form-group">
                            <input type="submit" value="修改" class="btn btn-primary">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

templates/student/index.html
{% extends "student/base.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h4>学生管理</h4>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-3">
                            <p><a href="/add" class="btn btn-info">添加学生</a></p>
                        </div>
                        <div class="col-md-9">
                            <form action="/student/search" class="row">
                                <input type="text" name="keyword" id="">
                                <select name="cate" id="">
                                    <option value="name">姓名</option>
                                    <option value="class">班级</option>
                                </select>

                                <input type="submit" name="" id="" class="btn btn-success" value="搜索">
                            </form>
                        </div>

                    </div>

                    <div class="table-responsive">
                        <table class="table table-striped table-hover">
                            <thead>
                            <tr>
                                <th>序号</th>
                                <th>姓名</th>
                                <th>年龄</th>
                                <th>性别</th>
                                <th>生日</th>
                                <th>班级</th>
                                <th>家庭住址</th>
                                <th>操作</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for student in student_list %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ student.name }}</td>
                                    <td>{{ student.age }}</td>
                                    <td>{{ student.get_sex_display }}</td>
                                    <td>{{ student.birthday|date:'Y-m-d' }}</td>
                                    <td>{{ student.clas.name }}</td>
                                    <td>
                                        {{ student.addr }}
                                    </td>
                                    <td>
                                        <a href="/student/edit/{{ student.id }}" class="btn btn-sm btn-warning">编辑</a>
                                        <a href="/student/delete/{{ student.id }}" class="btn btn-sm btn-danger">删除</a>
                                    </td>
                                </tr>

                            {% endfor %}

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

templates/student/search.html
{% extends 'student/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h4>学生管理</h4>
                </div>
                <div class="card-body">
                <div class="row">
                    <div class="col-md-3">
                        <p><a href="/student/add" class="btn btn-info">添加学生</a></p>
                    </div>
                    <div class="col-md-9">
                        <form action="/student/search" class="row">
                            <input type="text" name="keyword" id="" value="{{ keyword }}">
                            <select name="cate" id="">
                                {% if cate == 'name' %}
                                <option value="name" selected>姓名</option>
                                <option value="class">班级</option>
                                {% else %}
                                <option value="name">姓名</option>
                                <option value="class" selected>班级</option>
                                {% endif %}
                            </select>

                            <input type="submit" name="" id="" class="btn btn-success" value="搜索">
                        </form>
                    </div>

                </div>

                    <div class="table-responsive">
                        <table class="table table-striped table-hover">
                            <thead>
                            <tr>
                                <th>序号</th>
                                <th>姓名</th>
                                <th>年龄</th>
                                <th>性别</th>
                                <th>生日</th>
                                <th>班级</th>
                                <th>家庭住址</th>
                                <th>操作</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for student in student_list %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ student.name }}</td>
                                    <td>{{ student.age }}</td>
                                    <td>{{ student.get_sex_display }}</td>
                                    <td>{{ student.birthday|date:'Y-m-d' }}</td>
                                    <td>{{ student.clas.name }}</td>
                                    <td>
                                        {{ student.addr }}
                                    </td>
                                    <td>
                                        <a href="/student/edit/{{ student.id }}" class="btn btn-sm btn-warning">编辑</a>
                                        <a href="/student/delete/{{ student.id }}" class="btn btn-sm btn-danger">删除</a>
                                    </td>
                                </tr>

                            {% endfor %}

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}